### ISSUE TITLE
Make dummy test suite pass

### ISSUE THREAD

**Issue by Aagat** [ServerChef/serverchef-ui#2]
The dummy test fails with following error:

```
$ npm test
> countertop@0.1.0 test /home/travis/build/ServerChef/serverchef-ui
> react-scripts test --env=jsdom
 FAIL  src/App.test.js
  ● Test suite failed to run
    matchMedia not present, legacy browsers require a polyfill
      
      at Object.MediaQueryDispatch (node_modules/enquire.js/dist/enquire.js:226:19)
      at node_modules/enquire.js/dist/enquire.js:291:9
      at Object.<anonymous>.i (node_modules/enquire.js/dist/enquire.js:11:20)
      at Object.<anonymous> (node_modules/enquire.js/dist/enquire.js:21:2)
      at Object.<anonymous> (node_modules/react-responsive-mixin/index.js:2:28)
      at Object.<anonymous> (node_modules/react-slick/lib/slider.js:19:29)
      at Object.<anonymous> (node_modules/react-slick/lib/index.js:3:18)
      at Object.<anonymous> (node_modules/antd/lib/carousel/index.js:28:19)
      at Object.<anonymous> (node_modules/antd/lib/index.js:106:17)
      at Object.<anonymous> (src/App.js:2:39)
      at Object.<anonymous> (src/App.test.js:3:38)
      at process._tickCallback (internal/process/next_tick.js:103:7)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.203s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

It seems to have been fixed upstream [here](https://github.com/ant-design/ant-design/blob/cebf3a4c9eea91b49f25604e485e1cad3a206cfa/components/carousel/index.tsx#L1-L16)

**Comment by damo-da** [comment]
Fixed in #3

**Comment by damo-da** [comment]
Actually, I shouldn't be closing without the PR being accepted.

**Comment by Aagat** [comment]
Didn't want to eject just yet but this is cleaner than hacking polyfill into app itself.
